import { ResumeTemplate } from './templateModel';
import { SectionType } from './types';

const SIDEBAR_DEFAULT: SectionType[] = ['skills','languages','certifications','interests','social','portfolio','references'];
const MAIN_DEFAULT: SectionType[] = ['summary','objective','experience','projects','education','achievements','awards','publications','research','conferences','volunteer','membership','military','custom'];

export const TEMPLATES: ResumeTemplate[] = [
  {
    id: 'monolith', name: 'Monolith', category: 'Modern', atsScore: 96, atsSafe: true,
    blurb: 'Oversized condensed name with a bold red accent. Confident and impossible to ignore.',
    colors: { primary: '#0a0a0a', accent: '#e8341c', text: '#1a1a1a', muted: '#6b6b6b', surface: '#f5f5f5', onSurface: '#0a0a0a', page: '#ffffff' },
    typography: { headingFont: 'Arial Black, Arial, sans-serif', bodyFont: 'Arial, sans-serif', baseSize: 13, scale: 1.25, nameSize: 46, headingWeight: 800, headingTransform: 'uppercase', headingLetterSpacing: '0.02em' },
    spacing: { sectionGap: 20, itemGap: 12, pagePadding: 44 },
    headerStyle: 'big-name', dividerStyle: 'rule-thick',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
  {
    id: 'editorial', name: 'Editorial', category: 'Creative', atsScore: 91, atsSafe: true,
    blurb: 'Warm taupe palette with an elegant serif display name. Magazine-grade and refined.',
    colors: { primary: '#5b4a3f', accent: '#a07d5a', text: '#3a322c', muted: '#8a7d72', surface: '#f3ede4', onSurface: '#5b4a3f', page: '#fbf8f3' },
    typography: { headingFont: 'Playfair Display, Georgia, serif', bodyFont: 'Georgia, serif', baseSize: 13, scale: 1.2, nameSize: 38, headingWeight: 600, headingTransform: 'uppercase', headingLetterSpacing: '0.14em' },
    spacing: { sectionGap: 20, itemGap: 12, pagePadding: 48 },
    headerStyle: 'centered', dividerStyle: 'line',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: true,
  },
  {
    id: 'slate', name: 'Slate', category: 'Professional', atsScore: 90, atsSafe: true,
    blurb: 'Charcoal sidebar for skills and contact, clean white main column. Structured and strong.',
    colors: { primary: '#222831', accent: '#00a8a8', text: '#2b2b2b', muted: '#7a808a', surface: '#2b3138', onSurface: '#f2f4f6', page: '#ffffff' },
    typography: { headingFont: 'Arial, sans-serif', bodyFont: 'Arial, sans-serif', baseSize: 12, scale: 1.22, nameSize: 32, headingWeight: 700, headingTransform: 'uppercase', headingLetterSpacing: '0.08em' },
    spacing: { sectionGap: 16, itemGap: 11, pagePadding: 0 },
    headerStyle: 'plain', dividerStyle: 'line',
    layout: { type: 'sidebar-left', sidebarSections: SIDEBAR_DEFAULT, mainSections: MAIN_DEFAULT, sidebarWidth: 230 },
    showPhoto: true,
  },
  {
    id: 'azure', name: 'Azure', category: 'Modern', atsScore: 92, atsSafe: true,
    blurb: 'Electric royal-blue headings on white. Energetic, modern and crisply organized.',
    colors: { primary: '#1d4ed8', accent: '#2563eb', text: '#1e293b', muted: '#64748b', surface: '#eff4ff', onSurface: '#1d4ed8', page: '#ffffff' },
    typography: { headingFont: 'Verdana, Geneva, sans-serif', bodyFont: 'Verdana, Geneva, sans-serif', baseSize: 12, scale: 1.24, nameSize: 34, headingWeight: 700, headingTransform: 'uppercase', headingLetterSpacing: '0.06em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 36 },
    headerStyle: 'split', dividerStyle: 'underline',
    layout: { type: 'sidebar-left', sidebarSections: SIDEBAR_DEFAULT, mainSections: MAIN_DEFAULT, sidebarWidth: 220 },
    showPhoto: false,
  },
  {
    id: 'sage', name: 'Sage', category: 'Professional', atsScore: 93, atsSafe: true,
    blurb: 'Muted sage-green sidebar with airy serif headings. Calm, organic and quietly premium.',
    colors: { primary: '#5a6650', accent: '#7e8c6a', text: '#39402f', muted: '#828a76', surface: '#4f5a45', onSurface: '#eef0e7', page: '#fbfaf4' },
    typography: { headingFont: 'Optima, Candara, Georgia, serif', bodyFont: 'Georgia, serif', baseSize: 12, scale: 1.22, nameSize: 36, headingWeight: 500, headingTransform: 'uppercase', headingLetterSpacing: '0.12em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 0 },
    headerStyle: 'plain', dividerStyle: 'line',
    layout: { type: 'sidebar-left', sidebarSections: SIDEBAR_DEFAULT, mainSections: MAIN_DEFAULT, sidebarWidth: 225 },
    showPhoto: true,
  },
  {
    id: 'sterling', name: 'Sterling', category: 'ATS-Safe', atsScore: 98, atsSafe: true,
    blurb: 'Timeless grayscale minimalism with hairline rules. The safest possible parse, beautifully restrained.',
    colors: { primary: '#2d2d2d', accent: '#555555', text: '#2b2b2b', muted: '#888888', surface: '#f4f4f4', onSurface: '#2d2d2d', page: '#ffffff' },
    typography: { headingFont: 'Helvetica, Arial, sans-serif', bodyFont: 'Helvetica, Arial, sans-serif', baseSize: 13, scale: 1.2, nameSize: 30, headingWeight: 700, headingTransform: 'uppercase', headingLetterSpacing: '0.16em' },
    spacing: { sectionGap: 20, itemGap: 12, pagePadding: 48 },
    headerStyle: 'plain', dividerStyle: 'line',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
  {
    id: 'verdant', name: 'Verdant', category: 'Modern', atsScore: 94, atsSafe: true,
    blurb: 'Fresh mint-green section markers on a light sidebar layout. Friendly, modern and easy to scan.',
    colors: { primary: '#2f6b52', accent: '#3fa06f', text: '#27332c', muted: '#6f7d74', surface: '#e8f4ec', onSurface: '#2f6b52', page: '#ffffff' },
    typography: { headingFont: 'Trebuchet MS, Segoe UI, sans-serif', bodyFont: 'Segoe UI, Arial, sans-serif', baseSize: 12, scale: 1.22, nameSize: 34, headingWeight: 700, headingTransform: 'uppercase', headingLetterSpacing: '0.05em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 34 },
    headerStyle: 'plain', dividerStyle: 'line',
    layout: { type: 'sidebar-left', sidebarSections: SIDEBAR_DEFAULT, mainSections: MAIN_DEFAULT, sidebarWidth: 215 },
    showPhoto: false,
  },
  {
    id: 'noir', name: 'Noir', category: 'Executive', atsScore: 89, atsSafe: true,
    blurb: 'Black serif display with soft gold accents on cream. Luxurious, executive and understated.',
    colors: { primary: '#1a1a1a', accent: '#b08d57', text: '#2a2a2a', muted: '#8a8175', surface: '#efe9df', onSurface: '#1a1a1a', page: '#faf7f1' },
    typography: { headingFont: 'Didot, Bodoni MT, Georgia, serif', bodyFont: 'Georgia, serif', baseSize: 12, scale: 1.24, nameSize: 40, headingWeight: 600, headingTransform: 'uppercase', headingLetterSpacing: '0.18em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 0 },
    headerStyle: 'plain', dividerStyle: 'line',
    layout: { type: 'sidebar-left', sidebarSections: SIDEBAR_DEFAULT, mainSections: MAIN_DEFAULT, sidebarWidth: 230 },
    showPhoto: true,
  },
  {
    id: 'scarlet', name: 'Scarlet', category: 'Creative', atsScore: 90, atsSafe: true,
    blurb: 'High-contrast black and scarlet with a powerful display name. Bold, modern and assertive.',
    colors: { primary: '#111111', accent: '#d11f2a', text: '#1c1c1c', muted: '#6e6e6e', surface: '#f6f1f1', onSurface: '#111111', page: '#ffffff' },
    typography: { headingFont: 'Impact, Haettenschweiler, Arial, sans-serif', bodyFont: 'Arial, sans-serif', baseSize: 13, scale: 1.24, nameSize: 42, headingWeight: 800, headingTransform: 'uppercase', headingLetterSpacing: '0.03em' },
    spacing: { sectionGap: 20, itemGap: 12, pagePadding: 44 },
    headerStyle: 'big-name', dividerStyle: 'rule-thick',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
  {
    id: 'gazette', name: 'Gazette', category: 'Creative', atsScore: 88, atsSafe: true,
    blurb: 'A newspaper masthead treatment with classic serif type and ruled sections. Distinctive yet fully readable.',
    colors: { primary: '#1c1a17', accent: '#43403a', text: '#221f1b', muted: '#7c766c', surface: '#efe9dd', onSurface: '#1c1a17', page: '#f7f2e7' },
    typography: { headingFont: 'Playfair Display, Times New Roman, serif', bodyFont: 'Times New Roman, Georgia, serif', baseSize: 12, scale: 1.26, nameSize: 44, headingWeight: 700, headingTransform: 'uppercase', headingLetterSpacing: '0.1em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 44 },
    headerStyle: 'centered', dividerStyle: 'rule-thick',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
  {
    id: 'terminal', name: 'Terminal', category: 'Modern', atsScore: 85, atsSafe: true,
    blurb: 'A developer console aesthetic in monospace with a green accent. Distinctive for engineers, still text-selectable.',
    colors: { primary: '#1b2027', accent: '#1f9c6b', text: '#222831', muted: '#6b7480', surface: '#e7edf0', onSurface: '#1b2027', page: '#ffffff' },
    typography: { headingFont: 'Consolas, Menlo, Monaco, monospace', bodyFont: 'Consolas, Menlo, Monaco, monospace', baseSize: 12, scale: 1.2, nameSize: 32, headingWeight: 700, headingTransform: 'lowercase', headingLetterSpacing: '0.02em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 42 },
    headerStyle: 'plain', dividerStyle: 'line',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
  {
    id: 'vivid', name: 'Vivid', category: 'Creative', atsScore: 87, atsSafe: true,
    blurb: 'Vibrant magenta-to-violet energy with a big display name. Playful, marketing-forward and confident.',
    colors: { primary: '#7c1fa2', accent: '#d6256b', text: '#241827', muted: '#7a6e80', surface: '#f6e9f4', onSurface: '#7c1fa2', page: '#ffffff' },
    typography: { headingFont: 'Tahoma, Verdana, sans-serif', bodyFont: 'Tahoma, Verdana, sans-serif', baseSize: 12, scale: 1.24, nameSize: 40, headingWeight: 800, headingTransform: 'uppercase', headingLetterSpacing: '0.04em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 42 },
    headerStyle: 'big-name', dividerStyle: 'underline',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
  {
    id: 'product', name: 'Product', category: 'Modern', atsScore: 93, atsSafe: true,
    blurb: 'A clean product-landing feel in indigo and violet. Crisp, contemporary and tech-forward.',
    colors: { primary: '#4f46e5', accent: '#7c3aed', text: '#1f2430', muted: '#6b7280', surface: '#eef0fe', onSurface: '#4f46e5', page: '#ffffff' },
    typography: { headingFont: 'Segoe UI, Helvetica, Arial, sans-serif', bodyFont: 'Segoe UI, Helvetica, Arial, sans-serif', baseSize: 13, scale: 1.22, nameSize: 36, headingWeight: 700, headingTransform: 'none', headingLetterSpacing: '0em' },
    spacing: { sectionGap: 20, itemGap: 12, pagePadding: 46 },
    headerStyle: 'centered', dividerStyle: 'line',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
  {
    id: 'graphite', name: 'Graphite', category: 'Executive', atsScore: 91, atsSafe: true,
    blurb: 'A deep graphite sidebar paired with a roomy timeline-style main column. Corporate, polished and senior.',
    colors: { primary: '#3a3a3a', accent: '#9a9a9a', text: '#2c2c2c', muted: '#7d7d7d', surface: '#3d3d3d', onSurface: '#ededed', page: '#ffffff' },
    typography: { headingFont: 'Calibri, Candara, Segoe UI, sans-serif', bodyFont: 'Calibri, Candara, Segoe UI, sans-serif', baseSize: 12, scale: 1.22, nameSize: 34, headingWeight: 700, headingTransform: 'uppercase', headingLetterSpacing: '0.06em' },
    spacing: { sectionGap: 18, itemGap: 11, pagePadding: 0 },
    headerStyle: 'plain', dividerStyle: 'line',
    layout: { type: 'sidebar-left', sidebarSections: SIDEBAR_DEFAULT, mainSections: MAIN_DEFAULT, sidebarWidth: 235 },
    showPhoto: true,
  },
  {
    id: 'classic', name: 'Classic', category: 'Professional', atsScore: 95, atsSafe: true,
    blurb: 'A timeless centered serif layout with refined spacing. Elegant, conservative and universally trusted.',
    colors: { primary: '#222222', accent: '#4a4a4a', text: '#262626', muted: '#7a7a7a', surface: '#f2f2f2', onSurface: '#222222', page: '#ffffff' },
    typography: { headingFont: 'Garamond, Georgia, serif', bodyFont: 'Garamond, Georgia, serif', baseSize: 13, scale: 1.22, nameSize: 36, headingWeight: 600, headingTransform: 'uppercase', headingLetterSpacing: '0.14em' },
    spacing: { sectionGap: 20, itemGap: 12, pagePadding: 50 },
    headerStyle: 'centered', dividerStyle: 'line',
    layout: { type: 'single', sidebarSections: [], mainSections: MAIN_DEFAULT },
    showPhoto: false,
  },
];

export const TEMPLATE_MAP: Record<string, ResumeTemplate> = TEMPLATES.reduce(
  (acc, t) => { acc[t.id] = t; return acc; }, {} as Record<string, ResumeTemplate>,
);

export function getTemplate(id: string): ResumeTemplate {
  return TEMPLATE_MAP[id] || TEMPLATES[0];
}
